---
# Apache::Main
# 
# These tasks handle Apache related tasks, includes
## - install apache and php packages
## - turns on needed modules and status for monitoring
## - the included tasks handles Apache config files for whitneyhess.com.

- name: Apache::Main -- Install Apache and PHP Packages
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php5
   - php5-mysql
   - php5-memcache
   - php-apc

- name: Apache::Main -- Turn on status module
  shell: a2enmod status
  notify:
   - restart apache

- name: Apache::Main -- Turn on rewrite module
  shell: a2enmod rewrite
  notify:
   - restart apache

- name: Apache::Main -- Turn ExtendedStatus on
  shell: echo "ExtendedStatus On" >> /etc/apache2/httpd.conf
  notify:
   - restart apache

# includes task for handling Apache config files for whitneyhess.com
- include: files.yml